# Generated by Django 6.0 on 2026-01-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_imageupload_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
