# Generated by Django 6.0 on 2026-01-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_imageupload_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='description',
        ),
    ]
